server:
  port: 8001
  servlet:
    context-path: /
spring:
  application:
    name: CoreEngine
  data:
    elasticsearch:
      repositories:
        enabled: true
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
  main:
    allow-bean-definition-overriding: true

security:
  basic:
    enabled: false


draw:
  url: http://data.ny.gov/resource/d6yy-54nr.json

eureka:
  instance:
    hostname: eureka1
    lease-expiration-duration-in-seconds: 10
    lease-renewal-interval-in-seconds: 10
  server:
    eviction-interval-timer-in-ms: 5000
    enable-self-preservation: true
    renewal-threshold-update-interval-ms: 120000
    use-read-only-response-cache: false
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8001/eureka

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 10000
        loggerLevel: basic

management:
  security:
    enabled: false
  endpoint:
    info:
      enabled: true
  endpoints:
    web:
      cors:
        allowed-origins: "*"
        allowed-methods: GET, POST
      exposure:
        include: "*"
    enabled-by-default: true
  auditevents:
    enabled:

info:
  # static properties
  app:
    name: ${spring.application.name}
    description: --

logging:
  level:
    root: info
    com:
      netflix:
        discovery: 'OFF'
        eureka: 'OFF'
